Repository NBP-Quit/quit, pull requests merged in 2025-01, with the labels that each got.

#7 [chore] gateway 초기 설정
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  gateway-server/.gitattributes
  gateway-server/.gitignore
  gateway-server/build.gradle
  gateway-server/gradle/wrapper/gradle-wrapper.jar
  gateway-server/gradle/wrapper/gradle-wrapper.properties
  gateway-server/gradlew
  gateway-server/gradlew.bat
  gateway-server/settings.gradle
  gateway-server/src/main/java/com/quit/gateway/GatewayApplication.java
  gateway-server/src/main/resources/application.yml
  gateway-server/src/test/java/com/quit/gateway/GatewayApplicationTests.java
Labels: chore

#29 [feat] 리뷰 생성 기능 및 S3 이미지 업로드 기능 구현
  review/.gitattributes
  review/.gitignore
  review/build.gradle
  review/gradle/wrapper/gradle-wrapper.jar
  review/gradle/wrapper/gradle-wrapper.properties
  review/gradlew
  review/gradlew.bat
  review/settings.gradle
  review/src/main/java/com/quit/review/ReviewApplication.java
  review/src/main/java/com/quit/review/application/dto/ReviewCreateDto.java
  review/src/main/java/com/quit/review/application/dto/ScoresDto.java
  review/src/main/java/com/quit/review/application/service/ImageService.java
  review/src/main/java/com/quit/review/application/service/ImageServiceImpl.java
  review/src/main/java/com/quit/review/application/service/ReservationService.java
  review/src/main/java/com/quit/review/application/service/ReservationServiceImpl.java
  review/src/main/java/com/quit/review/application/service/ReviewService.java
  review/src/main/java/com/quit/review/application/service/ReviewServiceImpl.java
  review/src/main/java/com/quit/review/application/service/UserService.java
  review/src/main/java/com/quit/review/application/service/UserServiceImpl.java
  review/src/main/java/com/quit/review/common/ApiResponse.java
  review/src/main/java/com/quit/review/common/AuditorAwareImpl.java
  review/src/main/java/com/quit/review/common/AuditorProvider.java
  review/src/main/java/com/quit/review/common/BaseEntity.java
  review/src/main/java/com/quit/review/common/CustomApiException.java
  review/src/main/java/com/quit/review/common/GlobalExceptionHandler.java
  review/src/main/java/com/quit/review/domain/model/Image.java
  review/src/main/java/com/quit/review/domain/model/MealType.java
  review/src/main/java/com/quit/review/domain/model/Reply.java
  review/src/main/java/com/quit/review/domain/model/Review.java
  review/src/main/java/com/quit/review/domain/model/Scores.java
  review/src/main/java/com/quit/review/domain/repository/ReviewRepository.java
  review/src/main/java/com/quit/review/infrastructure/client/ReservationClient.java
  review/src/main/java/com/quit/review/infrastructure/client/ReservationResponse.java
  review/src/main/java/com/quit/review/infrastructure/client/UserClient.java
  review/src/main/java/com/quit/review/infrastructure/client/UserResponse.java
  review/src/main/java/com/quit/review/infrastructure/configuration/JpaConfig.java
  review/src/main/java/com/quit/review/infrastructure/configuration/S3Config.java
  review/src/main/java/com/quit/review/infrastructure/service/ImageUploader.java
  review/src/main/java/com/quit/review/infrastructure/service/S3Uploader.java
  review/src/main/java/com/quit/review/presentation/controller/ReviewController.java
  review/src/main/java/com/quit/review/presentation/request/ReviewCreateRequest.java
  review/src/main/java/com/quit/review/presentation/request/ScoresRequest.java
  review/src/test/java/com/quit/review/ReviewApplicationTests.java
  review/src/test/java/com/quit/review/application/service/ImageServiceTest.java
  review/src/test/java/com/quit/review/application/service/ReviewServiceTest.java
  review/src/test/java/com/quit/review/domain/model/ReviewTest.java
  review/src/test/java/com/quit/review/presentation/controller/ReviewControllerTest.java
  review/src/test/resources/test
  review/src/test/resources/test.jpg
  review/src/test/resources/test.txt
Labels: test, feat, chore

#31 [feat] 예약스케줄 생성, 수정, 삭제 조회 기능 구현
  store/src/main/java/com/quit/store/application/dto/ReservationSlotDto.java
  store/src/main/java/com/quit/store/application/dto/UpdateReservationSlotDto.java
  store/src/main/java/com/quit/store/application/dto/res/ReservationSlotResponse.java
  store/src/main/java/com/quit/store/application/dto/res/StoreResponse.java
  store/src/main/java/com/quit/store/application/service/ReservationSlotService.java
  store/src/main/java/com/quit/store/domain/entity/ReservationSlot.java
  store/src/main/java/com/quit/store/domain/repository/ReservationSlotRepository.java
  store/src/main/java/com/quit/store/domain/repository/ReservationSlotRepositoryCustom.java
  store/src/main/java/com/quit/store/domain/repository/ReservationSlotRepositoryImpl.java
  store/src/main/java/com/quit/store/presentation/controller/ReservationSlotController.java
  store/src/main/java/com/quit/store/presentation/dto/CreateReservationSlotRequest.java
  store/src/main/java/com/quit/store/presentation/dto/UpdateReservationSlotRequest.java
  store/src/main/java/com/quit/store/presentation/exception/ErrorType.java
  store/src/main/java/com/quit/store/presentation/exception/GlobalExceptionHandler.java
Labels: feat

#30 [feat] 로그인 및 회원 CRUD 구현
  user-server/build.gradle
  user-server/src/main/java/com/quit/user/application/dto/TokenDto.java
  user-server/src/main/java/com/quit/user/common/filter/JwtAuthenticationFilter.java
  user-server/src/main/java/com/quit/user/common/jwt/JwtUtil.java
  user-server/src/main/java/com/quit/user/common/security/UserDetailsImpl.java
  user-server/src/main/java/com/quit/user/common/security/UserDetailsServiceImpl.java
  user-server/src/main/java/com/quit/user/common/security/WebSecurityConfig.java
  user-server/src/main/java/com/quit/user/domain/model/User.java
  user-server/src/main/java/com/quit/user/domain/service/AuthService.java
  user-server/src/main/java/com/quit/user/domain/service/UserService.java
  user-server/src/main/java/com/quit/user/infrastructure/config/PasswordEncoderConfig.java
  user-server/src/main/java/com/quit/user/presentation/controller/AuthController.java
  user-server/src/main/java/com/quit/user/presentation/controller/UserController.java
  user-server/src/main/java/com/quit/user/presentation/request/LoginRequest.java
  user-server/src/main/resources/application.yml
  user-server/userTest.http
Labels: docs, feat, chore

#34 [feat] 대기열 갱신 요청 처리 및 GlobalExceptionHandler 적용
  queue/src/main/java/com/quit/queue/application/service/QueueService.java
  queue/src/main/java/com/quit/queue/presentation/controller/QueueController.java
  queue/src/main/java/com/quit/queue/presentation/exception/handler/GlobalExceptionHandler.java
Labels: feat, refactor

#40 [feat] 결제 생성, 취소, 예약 건별 조회 기능 구현
  payment/.gitattributes
  payment/.gitignore
  payment/build.gradle
  payment/gradle/wrapper/gradle-wrapper.jar
  payment/gradle/wrapper/gradle-wrapper.properties
  payment/gradlew
  payment/gradlew.bat
  payment/settings.gradle
  payment/src/main/java/com/quit/payment/PaymentApplication.java
  payment/src/main/java/com/quit/payment/application/dto/PaymentDto.java
  payment/src/main/java/com/quit/payment/application/dto/TempPaymentDto.java
  payment/src/main/java/com/quit/payment/application/dto/res/PaymentResponse.java
  payment/src/main/java/com/quit/payment/application/dto/res/TempPaymentResponse.java
  payment/src/main/java/com/quit/payment/application/service/PaymentService.java
  payment/src/main/java/com/quit/payment/common/dto/ApiResponse.java
  payment/src/main/java/com/quit/payment/common/model/BaseEntity.java
  payment/src/main/java/com/quit/payment/configuration/AuditorAwareImpl.java
  payment/src/main/java/com/quit/payment/configuration/JpaConfig.java
  payment/src/main/java/com/quit/payment/configuration/PaymentAuthInterceptor.java
  payment/src/main/java/com/quit/payment/configuration/PaymentFeignConfig.java
  payment/src/main/java/com/quit/payment/configuration/PaymentProperties.java
  payment/src/main/java/com/quit/payment/domain/entity/Payment.java
  payment/src/main/java/com/quit/payment/domain/entity/Status.java
  payment/src/main/java/com/quit/payment/domain/entity/TempPayment.java
  payment/src/main/java/com/quit/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/quit/payment/domain/repository/TempPaymentRepository.java
  payment/src/main/java/com/quit/payment/infrastructure/client/PaymentClient.java
  payment/src/main/java/com/quit/payment/infrastructure/client/PaymentGateway.java
  payment/src/main/java/com/quit/payment/infrastructure/client/PaymentGatewayImpl.java
  payment/src/main/java/com/quit/payment/infrastructure/dto/CancelPaymentResponse.java
  payment/src/main/java/com/quit/payment/infrastructure/dto/ConfirmPaymentResponse.java
  payment/src/main/java/com/quit/payment/presentation/controller/PaymentController.java
  payment/src/main/java/com/quit/payment/presentation/dto/CancelPaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/dto/CreatePaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/dto/CreateTempPaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/exception/CustomErrorResponse.java
  payment/src/main/java/com/quit/payment/presentation/exception/CustomException.java
  payment/src/main/java/com/quit/payment/presentation/exception/ErrorType.java
  payment/src/main/java/com/quit/payment/presentation/exception/GlobalExceptionHandler.java
  payment/src/main/resources/application.yml
  payment/src/test/java/com/quit/payment/PaymentApplicationTests.java
Labels: feat, refactor, chore

#47 [feat] 대기열 순번 도달 처리 및 예약 서비스 진입
  queue/build.gradle
  queue/src/main/java/com/quit/queue/QueueApplication.java
  queue/src/main/java/com/quit/queue/application/dto/ReservationDto.java
  queue/src/main/java/com/quit/queue/application/dto/res/QueueResponse.java
  queue/src/main/java/com/quit/queue/application/messaging/ReservationMessage.java
  queue/src/main/java/com/quit/queue/application/scheduler/QueueScheduler.java
  queue/src/main/java/com/quit/queue/application/service/QueueService.java
  queue/src/main/java/com/quit/queue/infrastructure/configuration/ProducerApplicationKafkaConfig.java
  queue/src/main/java/com/quit/queue/infrastructure/configuration/RedisConfig.java
  queue/src/main/java/com/quit/queue/infrastructure/messaging/KafkaMessageProducer.java
  queue/src/main/java/com/quit/queue/presentation/controller/QueueController.java
  queue/src/main/java/com/quit/queue/presentation/request/ReservationRequest.java
  queue/src/main/resources/application.yml
  queue/src/test/java/com/quit/queue/application/service/QueueServiceTest.java
  queue/src/test/java/com/quit/queue/application/service/infrastructure/messaging/KafkaMessageProducerTest.java
Labels: feat, refactor, chore

#52 [refactor] 대기열 리팩토링
  queue/src/main/java/com/quit/queue/application/scheduler/QueueScheduler.java
  queue/src/main/java/com/quit/queue/application/service/QueueService.java
Labels: refactor

#50 [feat] JWT 인증 및 인가 로직 추가 / 헤더를 통한 사용자 정보 처리
  gateway-server/.gitignore
  gateway-server/build.gradle
  gateway-server/src/main/java/com/quit/gateway/common/jwt/JwtUtil.java
  gateway-server/src/main/java/com/quit/gateway/dto/CustomHeader.java
  gateway-server/src/main/java/com/quit/gateway/infrastructure/config/PasswordConfig.java
  gateway-server/src/main/java/com/quit/gateway/infrastructure/config/SecurityConfig.java
  gateway-server/src/main/resources/application.yml
  user-server/src/main/java/com/quit/user/application/service/AuthService.java
  user-server/src/main/java/com/quit/user/application/service/UserService.java
  user-server/src/main/java/com/quit/user/common/filter/JwtAuthenticationFilter.java
  user-server/src/main/java/com/quit/user/common/filter/JwtAuthorizationFilter.java
  user-server/src/main/java/com/quit/user/common/jwt/JwtUtil.java
  user-server/src/main/java/com/quit/user/common/security/WebSecurityConfig.java
  user-server/src/main/java/com/quit/user/domain/service/UserService.java
  user-server/src/main/java/com/quit/user/presentation/controller/AuthController.java
  user-server/src/main/java/com/quit/user/presentation/controller/UserController.java
Labels: feat, refactor, chore

#54 [feat] 결제 서비스 kafka 적용
  payment/build.gradle
  payment/docker-compose.yml
  payment/src/main/java/com/quit/payment/application/dto/PaymentEvent.java
  payment/src/main/java/com/quit/payment/application/service/PaymentService.java
  payment/src/main/java/com/quit/payment/domain/entity/Payment.java
  payment/src/main/java/com/quit/payment/infrastructure/client/PaymentClient.java
  payment/src/main/java/com/quit/payment/infrastructure/client/ReservationClient.java
  payment/src/main/java/com/quit/payment/infrastructure/client/ReservationGateway.java
  payment/src/main/java/com/quit/payment/infrastructure/client/ReservationGatewayImpl.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/AuditorAwareImpl.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/JpaConfig.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/PaymentAuthInterceptor.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/PaymentFeignConfig.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/PaymentProperties.java
  payment/src/main/java/com/quit/payment/infrastructure/dto/ReservationResponse.java
  payment/src/main/java/com/quit/payment/infrastructure/kafka/KafkaProducer.java
  payment/src/main/java/com/quit/payment/infrastructure/kafka/KafkaProducerConfig.java
  payment/src/main/java/com/quit/payment/infrastructure/kafka/KafkaProperties.java
  payment/src/main/java/com/quit/payment/presentation/controller/PaymentController.java
  payment/src/main/java/com/quit/payment/presentation/exception/ErrorType.java
  payment/src/main/resources/application.yml
Labels: feat, refactor, chore

#57 [feat] 가게 서비스 kafka 적용
  payment/build.gradle
  payment/src/main/java/com/quit/payment/application/dto/ReservationEvent.java
  payment/src/test/java/com/quit/payment/PaymentApplicationTests.java
  store/build.gradle
  store/src/main/java/com/quit/store/application/dto/ReservationEvent.java
  store/src/main/java/com/quit/store/application/service/ReservationSlotService.java
  store/src/main/java/com/quit/store/domain/entity/ReservationSlot.java
  store/src/main/java/com/quit/store/infrastructure/kafka/KafkaConsumerConfig.java
  store/src/main/java/com/quit/store/infrastructure/kafka/KafkaProperties.java
  store/src/main/java/com/quit/store/presentation/exception/ErrorType.java
  store/src/main/resources/application.yml
Labels: test, feat, chore

#58 [feat] 로그인 시 rate limit 적용
  gateway-server/build.gradle
  gateway-server/src/main/java/com/quit/gateway/infrastructure/config/RateLimitConfig.java
  gateway-server/src/main/resources/application.yml
  user-server/src/main/java/com/quit/user/application/service/UserService.java
  user-server/src/main/java/com/quit/user/domain/enums/UserRoleEnum.java
  user-server/userTest.http
Labels: feat

#55 [feat] 서비스 모니터링
  prometheus/docker-compose.yml
  prometheus/prometheus.yml
  queue/build.gradle
  queue/src/main/java/com/quit/queue/infrastructure/filter/PrometheusAuthorizationFilter.java
  queue/src/main/resources/application.yml
  queue/src/main/resources/static/favicon.ico
Labels: feat, chore

#62 [fix] Rate Limit 적용 후 조회가 안되는 현상 수정
  gateway-server/src/main/java/com/quit/gateway/infrastructure/config/RateLimitConfig.java
  gateway-server/src/main/resources/application.yml
  user-server/src/main/java/com/quit/user/application/service/UserService.java
Labels: fix

#67 [feat] 가게 서비스 권한 검증 로직 추가 및 가게 조회 내부용 API 구현
  gateway-server/src/main/resources/application.yml
  payment/src/main/java/com/quit/payment/application/service/PaymentService.java
  payment/src/main/java/com/quit/payment/infrastructure/client/ReservationClient.java
  payment/src/main/java/com/quit/payment/infrastructure/client/ReservationGateway.java
  payment/src/main/java/com/quit/payment/infrastructure/client/ReservationGatewayImpl.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/AuditorAwareImpl.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/CustomErrorDecoder.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/FeignClientConfig.java
  payment/src/main/java/com/quit/payment/infrastructure/configuration/PaymentFeignConfig.java
  payment/src/main/java/com/quit/payment/infrastructure/dto/ReservationResponse.java
  payment/src/main/java/com/quit/payment/presentation/exception/ErrorType.java
  payment/src/main/resources/application.yml
  store/src/main/java/com/quit/store/application/service/ReservationSlotService.java
  store/src/main/java/com/quit/store/application/service/StoreService.java
  store/src/main/java/com/quit/store/common/util/RoleValidator.java
  store/src/main/java/com/quit/store/domain/repository/StoreRepository.java
  store/src/main/java/com/quit/store/infrastructure/configuration/AuditorAwareImpl.java
  store/src/main/java/com/quit/store/presentation/controller/ReservationSlotController.java
  store/src/main/java/com/quit/store/presentation/controller/StoreController.java
  store/src/main/java/com/quit/store/presentation/exception/ErrorType.java
Labels: feat

#69 [feat] 대기열 추가 시 가게 존재 여부 검증 및 권한 검증 리팩토링
  queue/src/main/java/com/quit/queue/application/service/QueueService.java
  queue/src/main/java/com/quit/queue/application/service/RoleValidationService.java
  queue/src/main/java/com/quit/queue/application/service/StoreService.java
  queue/src/main/java/com/quit/queue/infrastructure/client/StoreClient.java
  queue/src/main/resources/application.yml
Labels: feat, refactor, chore

#75 [refactor] Kafka 토픽 이름 변경
  queue/src/main/java/com/quit/queue/application/scheduler/QueueScheduler.java
Labels: refactor

#77 [feat] 권한 요청, 요청 확인, 수정 기능 추가
  user-server/src/main/java/com/quit/user/application/dto/RequestRoleDto.java
  user-server/src/main/java/com/quit/user/application/dto/RequestStatusDto.java
  user-server/src/main/java/com/quit/user/application/service/UserService.java
  user-server/src/main/java/com/quit/user/common/security/UserDetailsServiceImpl.java
  user-server/src/main/java/com/quit/user/domain/enums/RequestStatus.java
  user-server/src/main/java/com/quit/user/domain/model/RequestRole.java
  user-server/src/main/java/com/quit/user/domain/model/User.java
  user-server/src/main/java/com/quit/user/infrastructure/repository/RequestRoleRepository.java
  user-server/src/main/java/com/quit/user/infrastructure/repository/UserRepository.java
  user-server/src/main/java/com/quit/user/presentation/controller/UserController.java
  user-server/src/main/java/com/quit/user/presentation/request/RoleRequest.java
  user-server/userTest.http
Labels: feat

#82 [feat] 가게, 결제 서비스 코드 리팩토링
  payment/src/main/java/com/quit/payment/application/dto/ReservationEvent.java
  payment/src/main/java/com/quit/payment/application/dto/res/PaymentResponse.java
  payment/src/main/java/com/quit/payment/application/service/PaymentService.java
  payment/src/main/java/com/quit/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/quit/payment/presentation/dto/CancelPaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/dto/CreatePaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/dto/CreateTempPaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/exception/ErrorType.java
  payment/src/test/java/com/quit/payment/PaymentApplicationTests.java
Labels: feat, refactor

#70 [feat] 리뷰 좋아요 기능 및 상점 평균 별점 기능 구현
  review/build.gradle
  review/src/main/java/com/quit/review/application/dto/AvgScoresDto.java
  review/src/main/java/com/quit/review/application/dto/ReviewResponse.java
  review/src/main/java/com/quit/review/application/dto/ReviewSimpleResponse.java
  review/src/main/java/com/quit/review/application/dto/ReviewSummeryResponse.java
  review/src/main/java/com/quit/review/application/service/CacheService.java
  review/src/main/java/com/quit/review/application/service/ImageServiceImpl.java
  review/src/main/java/com/quit/review/application/service/ImageUploader.java
  review/src/main/java/com/quit/review/application/service/LikeAction.java
  review/src/main/java/com/quit/review/application/service/LikeEvent.java
  review/src/main/java/com/quit/review/application/service/MessagePublisher.java
  review/src/main/java/com/quit/review/application/service/ReviewService.java
  review/src/main/java/com/quit/review/application/service/ReviewServiceImpl.java
  review/src/main/java/com/quit/review/domain/model/Like.java
  review/src/main/java/com/quit/review/domain/model/Review.java
  review/src/main/java/com/quit/review/domain/repository/LikeRepository.java
  review/src/main/java/com/quit/review/domain/repository/ReviewRepository.java
  review/src/main/java/com/quit/review/infrastructure/configuration/RabbitMqConfig.java
  review/src/main/java/com/quit/review/infrastructure/configuration/RedisConfig.java
  review/src/main/java/com/quit/review/infrastructure/service/LikeEventListener.java
  review/src/main/java/com/quit/review/infrastructure/service/RabbitMqMessagePublisher.java
  review/src/main/java/com/quit/review/infrastructure/service/RedisService.java
  review/src/main/java/com/quit/review/infrastructure/service/S3Uploader.java
  review/src/main/java/com/quit/review/presentation/controller/ReviewController.java
  review/src/test/java/com/quit/review/application/service/ImageServiceTest.java
Labels: feat

#86 [test] 가게 및 결제 서비스 테스트 코드 추가
  payment/src/main/java/com/quit/payment/infrastructure/dto/CancelPaymentResponse.java
  payment/src/main/java/com/quit/payment/infrastructure/dto/ConfirmPaymentResponse.java
  payment/src/test/java/com/quit/payment/PaymentServiceTest.java
  store/src/test/java/com/quit/store/ReservationSlotServiceTest.java
Labels: test

#90 [test] 대기열 테스트 코드 작성 및 수정
  queue/src/test/java/com/quit/queue/application/service/QueueServiceTest.java
Labels: test

#88 [fix] 리뷰 캐싱 처리 및 조회 쿼리 수정, 코드 리팩토링
  review/src/main/java/com/quit/review/application/dto/AvgScoresDto.java
  review/src/main/java/com/quit/review/application/dto/RatingDetailsDto.java
  review/src/main/java/com/quit/review/application/dto/ReviewCreateDto.java
  review/src/main/java/com/quit/review/application/dto/ReviewResponse.java
  review/src/main/java/com/quit/review/application/dto/ReviewSimpleResponse.java
  review/src/main/java/com/quit/review/application/dto/ReviewSummeryResponse.java
  review/src/main/java/com/quit/review/application/dto/ReviewUpdateDto.java
  review/src/main/java/com/quit/review/application/dto/ScoresDto.java
  review/src/main/java/com/quit/review/application/service/CacheService.java
  review/src/main/java/com/quit/review/application/service/ReviewService.java
  review/src/main/java/com/quit/review/application/service/ReviewServiceImpl.java
  review/src/main/java/com/quit/review/domain/model/Like.java
  review/src/main/java/com/quit/review/domain/model/RatingDetails.java
  review/src/main/java/com/quit/review/domain/model/Reply.java
  review/src/main/java/com/quit/review/domain/model/Review.java
  review/src/main/java/com/quit/review/domain/model/Tag.java
  review/src/main/java/com/quit/review/domain/repository/ReviewRepository.java
  review/src/main/java/com/quit/review/infrastructure/configuration/RedisConfig.java
  review/src/main/java/com/quit/review/infrastructure/repository/ReviewRepositoryCustom.java
  review/src/main/java/com/quit/review/infrastructure/repository/ReviewRepositoryImpl.java
  review/src/main/java/com/quit/review/infrastructure/service/RedisService.java
  review/src/main/java/com/quit/review/presentation/controller/ReviewController.java
  review/src/main/java/com/quit/review/presentation/request/RatingDetailsRequest.java
  review/src/main/java/com/quit/review/presentation/request/ReviewCreateRequest.java
  review/src/main/java/com/quit/review/presentation/request/ReviewUpdateRequest.java
  review/src/test/java/com/quit/review/application/service/ReviewServiceTest.java
  review/src/test/java/com/quit/review/domain/model/ReviewTest.java
  review/src/test/java/com/quit/review/presentation/controller/ReviewControllerTest.java
Labels: refactor, fix

#95 [feat] 일정 기간의 예약 스케줄 생성 기능 구현
  store/src/main/java/com/quit/store/application/dto/BatchReservationSlotsDto.java
  store/src/main/java/com/quit/store/application/service/ReservationSlotService.java
  store/src/main/java/com/quit/store/domain/repository/ReservationSlotRepositoryCustom.java
  store/src/main/java/com/quit/store/domain/repository/ReservationSlotRepositoryImpl.java
  store/src/main/java/com/quit/store/presentation/controller/ReservationSlotController.java
  store/src/main/java/com/quit/store/presentation/dto/BatchReservationSlotsRequest.java
  store/src/main/java/com/quit/store/presentation/dto/UpdateReservationSlotRequest.java
  store/src/main/java/com/quit/store/presentation/exception/ErrorType.java
  store/src/test/java/com/quit/store/ReservationSlotServiceTest.java
Labels: test, feat, refactor

#100 [feat] 대기열 멀티 인스턴스 적용 및 과부하 해결
  queue/src/main/java/com/quit/queue/application/scheduler/QueueScheduler.java
  queue/src/main/java/com/quit/queue/application/service/QueueService.java
  queue/src/main/java/com/quit/queue/application/service/RoleValidationService.java
  queue/src/main/java/com/quit/queue/application/service/StoreServerAssignmentService.java
  queue/src/main/java/com/quit/queue/common/RoleValidationType.java
  queue/src/main/java/com/quit/queue/infrastructure/util/ServerInfo.java
  queue/src/main/java/com/quit/queue/presentation/controller/StoreServerAssignmentController.java
  store/build.gradle
  store/src/main/java/com/quit/store/StoreApplication.java
  store/src/main/java/com/quit/store/application/service/QueueClientService.java
  store/src/main/java/com/quit/store/application/service/StoreService.java
  store/src/main/java/com/quit/store/infrastructure/client/QueueClient.java
Labels: feat, refactor, chore

#102 [feat] 예약 슬롯 캐싱 적용
  store/src/main/java/com/quit/store/application/dto/res/GetReservationSlotResponse.java
  store/src/main/java/com/quit/store/application/service/ReservationSlotService.java
  store/src/main/java/com/quit/store/infrastructure/configuration/CacheConfig.java
  store/src/main/java/com/quit/store/presentation/controller/ReservationSlotController.java
Labels: feat

#110 [feat] email 값으로 유저 정보 조회
  store/src/main/java/com/quit/store/presentation/controller/StoreController.java
  user-server/src/main/java/com/quit/user/application/dto/UserDto.java
  user-server/src/main/java/com/quit/user/application/service/AuthService.java
  user-server/src/main/java/com/quit/user/application/service/UserService.java
  user-server/src/main/java/com/quit/user/domain/model/User.java
  user-server/src/main/java/com/quit/user/infrastructure/repository/UserRepository.java
  user-server/src/main/java/com/quit/user/presentation/controller/UserController.java
  user-server/src/main/java/com/quit/user/presentation/request/SignupRequest.java
Labels: feat, refactor

#114 [refactor] 대기열 추가 시 점수의 동시성 문제 해결 및 API RestFul하게 변경, 대기시 순번을 확인할 수 있는 waiting-room API 추가
  queue/build.gradle
  queue/src/main/java/com/quit/queue/application/scheduler/QueueCounterResetScheduler.java
  queue/src/main/java/com/quit/queue/application/scheduler/QueueScheduler.java
  queue/src/main/java/com/quit/queue/application/service/QueueService.java
  queue/src/main/java/com/quit/queue/presentation/controller/StoreServerAssignmentController.java
  queue/src/main/java/com/quit/queue/presentation/controller/WaitingRoomController.java
  queue/src/main/resources/application.yml
  queue/src/main/resources/templates/waiting-room.html
Labels: feat, refactor, chore

#115 [feat] 프로젝트 초기 설정 및 슬랙 DM 알림 전송 기능 구현
  notification/.gitattributes
  notification/.gitignore
  notification/build.gradle
  notification/gradle/wrapper/gradle-wrapper.jar
  notification/gradle/wrapper/gradle-wrapper.properties
  notification/gradlew
  notification/gradlew.bat
  notification/settings.gradle
  notification/src/main/java/com/quit/notification/NotificationApplication.java
  notification/src/main/java/com/quit/notification/application/service/NotificationService.java
  notification/src/main/java/com/quit/notification/application/service/NotificationServiceImpl.java
  notification/src/main/java/com/quit/notification/application/service/SlackNotificationService.java
  notification/src/main/java/com/quit/notification/application/service/StoreService.java
  notification/src/main/java/com/quit/notification/application/service/StoreServiceImpl.java
  notification/src/main/java/com/quit/notification/application/service/UserService.java
  notification/src/main/java/com/quit/notification/application/service/UserServiceImpl.java
  notification/src/main/java/com/quit/notification/common/ApiResponse.java
  notification/src/main/java/com/quit/notification/infrastructure/client/StoreClient.java
  notification/src/main/java/com/quit/notification/infrastructure/client/UserClient.java
  notification/src/main/java/com/quit/notification/infrastructure/configuration/KafkaConsumerConfig.java
  notification/src/main/java/com/quit/notification/infrastructure/configuration/KafkaProducerConfig.java
  notification/src/main/java/com/quit/notification/infrastructure/configuration/SlackConfig.java
  notification/src/main/java/com/quit/notification/infrastructure/dto/StoreResponse.java
  notification/src/main/java/com/quit/notification/infrastructure/dto/UserResponse.java
  notification/src/main/java/com/quit/notification/infrastructure/messaging/KafkaMessageConsumer.java
  notification/src/main/java/com/quit/notification/infrastructure/messaging/message/ReservationEvent.java
  notification/src/main/java/com/quit/notification/infrastructure/messaging/message/ReservationMessage.java
  notification/src/main/java/com/quit/notification/infrastructure/service/SlackNotificationServiceImpl.java
  notification/src/main/resources/application.yml
  notification/src/test/java/com/quit/notification/NotificationApplicationTests.java
  notification/src/test/java/com/quit/notification/infrastructure/service/SlackNotificationServiceImplTest.java
  review/src/test/java/com/quit/review/application/service/ReviewServiceTest.java
  review/src/test/java/com/quit/review/presentation/controller/ReviewControllerTest.java
Labels: feat, chore

#121 [feat] 가게 서비스 예약 스케줄 동시성 문제 해결
  payment/src/main/resources/application.yml
  store/build.gradle
  store/src/main/java/com/quit/store/application/service/ReservationSlotService.java
  store/src/main/java/com/quit/store/infrastructure/kafka/KafkaMessageListener.java
  store/src/main/java/com/quit/store/infrastructure/redis/AopForTransaction.java
  store/src/main/java/com/quit/store/infrastructure/redis/CacheConfig.java
  store/src/main/java/com/quit/store/infrastructure/redis/CustomSpringELParser.java
  store/src/main/java/com/quit/store/infrastructure/redis/DistributedLock.java
  store/src/main/java/com/quit/store/infrastructure/redis/DistributedLockAop.java
  store/src/main/java/com/quit/store/infrastructure/redis/RedisProperties.java
  store/src/main/java/com/quit/store/infrastructure/redis/RedissonConfig.java
  store/src/main/java/com/quit/store/presentation/controller/ReservationSlotController.java
  store/src/main/java/com/quit/store/presentation/controller/StoreController.java
  store/src/main/resources/application.yml
Labels: feat, refactor

#119 [feat] prometheus에 queue외 다른 서비스 연결
  payment/build.gradle
  payment/src/main/java/com/quit/payment/infrastructure/filter/PrometheusAuthorizationFilter.java
  payment/src/main/resources/application.yml
  payment/src/main/resources/static/favicon.ico
  prometheus/prometheus.yml
  queue/src/main/java/com/quit/queue/infrastructure/filter/PrometheusAuthorizationFilter.java
  reservation/build.gradle
  reservation/src/main/java/com/quit/reservation/infrastructure/filter/PrometheusAuthorizationFilter.java
  reservation/src/main/resources/application.yml
  reservation/src/main/resources/static/favicon.ico
  review/build.gradle
  review/src/main/java/com/quit/review/infrastructure/filter/PrometheusAuthorizationFilter.java
  review/src/main/resources/application.yml
  review/src/main/resources/static/favicon.ico
  store/build.gradle
  store/src/main/java/com/quit/store/infrastructure/filter/PrometheusAuthorizationFilter.java
  store/src/main/resources/application.yml
  store/src/main/resources/static/favicon.ico
  user-server/build.gradle
  user-server/src/main/java/com/quit/user/infrastructure/filter/PrometheusAuthorizationFilter.java
  user-server/src/main/resources/application.yml
  user-server/src/main/resources/static/favicon.ico
Labels: feat, chore

#123 [feat] 가게 소유권 확인 api 구현
  store/src/main/java/com/quit/store/application/service/StoreService.java
  store/src/main/java/com/quit/store/presentation/controller/StoreController.java
Labels: feat, refactor

#130 [feat] 결제 승인 및 취소 요청 멱등키 적용
  payment/build.gradle
  payment/src/main/java/com/quit/payment/application/dto/CancelPaymentDto.java
  payment/src/main/java/com/quit/payment/application/dto/PaymentDto.java
  payment/src/main/java/com/quit/payment/application/service/IdempotencyService.java
  payment/src/main/java/com/quit/payment/application/service/PaymentService.java
  payment/src/main/java/com/quit/payment/infrastructure/client/PaymentClient.java
  payment/src/main/java/com/quit/payment/infrastructure/client/PaymentGateway.java
  payment/src/main/java/com/quit/payment/infrastructure/client/PaymentGatewayImpl.java
  payment/src/main/java/com/quit/payment/infrastructure/redis/CacheConfig.java
  payment/src/main/java/com/quit/payment/infrastructure/redis/RedisProperties.java
  payment/src/main/java/com/quit/payment/presentation/dto/CancelPaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/dto/CreatePaymentRequest.java
  payment/src/main/java/com/quit/payment/presentation/exception/ErrorType.java
  payment/src/main/resources/application.yml
Labels: feat, refactor

#134 [feat] 가게 서비스에 캐싱 적용
  store/src/main/java/com/quit/store/application/service/StoreService.java
  store/src/main/java/com/quit/store/infrastructure/redis/CacheConfig.java
Labels: feat

#141 :bug: fix: 가게 -> 대기열 서버 등록 feign client 오류
  store/src/main/java/com/quit/store/infrastructure/client/QueueClient.java
Labels: fix

#142 [fix] store에 QUEUE_FEIGN_URL 환경 변수 추가, rabbitMQ 삭제
  .github/workflows/quit CI.yml
  docker-compose.yml
  docker-deploy-compose.yml
  review-deploy-compose.yml
  review/Dockerfile
  store/Dockerfile
Labels: fix

#146 [fix] kafka ec2 분리
  .github/workflows/quit CI.yml
  docker-deploy-compose.yml
  kafka-deploy-compose.yml
  notification-deploy-compose.yml
  payment-deploy-compose.yml
  queue-compose.yml
  reservation-deploy-compose.yml
  user/userTest.http
Labels: fix

#157 [fix] 프로메테우스 pavicon 추가
  user/src/main/resources/static/favicon.ico
Labels: fix

#159 [refactor] 비동기 스케줄러 처리 방식 개선
  queue/src/main/java/com/quit/queue/application/scheduler/QueueCounterResetScheduler.java
Labels: refactor
